name: Go Code Format Check

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install gofmt
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Run gofmt
        run: |
          diff=$(gofmt -l .)
          if [ -n "$diff" ]; then
            echo "Check 'gofmt -w .' to fix gofmt"
            echo "$diff"
            exit 1
          fi

      - name: Run goimports
        run: |
          diff=$(goimports -l .)
          if [ -n "$diff" ]; then
            echo "Check 'goimports -w .' to fix imports"
            echo "$diff"
            exit 1
          fi

      - name: Run tests
        run: |
          go test ./...
